// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzw_kpI5d5kkmDqWd-TcQ8gPiUJyvhPNo',
    appId: '1:179535803734:web:05cfeae665d6f5f91e52f7',
    messagingSenderId: '179535803734',
    projectId: 'webapp-finalproject',
    authDomain: 'webapp-finalproject.firebaseapp.com',
    storageBucket: 'webapp-finalproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5zto3FZ65x9mUgbMc2LpKacsMZDYWwc4',
    appId: '1:179535803734:android:f2446f4637cb62b81e52f7',
    messagingSenderId: '179535803734',
    projectId: 'webapp-finalproject',
    storageBucket: 'webapp-finalproject.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzw_kpI5d5kkmDqWd-TcQ8gPiUJyvhPNo',
    appId: '1:179535803734:web:05c9636eec8f0b7d1e52f7',
    messagingSenderId: '179535803734',
    projectId: 'webapp-finalproject',
    authDomain: 'webapp-finalproject.firebaseapp.com',
    storageBucket: 'webapp-finalproject.appspot.com',
  );
}
